### ISSUE TITLE
compiler:  not implemented handling of `*ast.IndexListExpr` in substituteTypeArgs function

### ISSUE THREAD

**Issue by iamrajiv** [dispatchrun/coroutine#141]
## Description

When I run `examples/scrape`, I am getting the below error:

```shell
➜  scrape git:(perf) ✗ make
./coroc .
2024/02/11 06:42:14.710485 reading, parsing and type-checking
2024/02/11 06:42:15.271370 building SSA program
2024/02/11 06:42:15.477581 building callgraph using vta algorithm
2024/02/11 06:42:15.849120 collecting generic instances
2024/02/11 06:42:15.849958 finding yield points
2024/02/11 06:42:15.849980 coloring functions
2024/02/11 06:42:15.850092 compiling package main
2024/02/11 06:42:15.851580 compiling function main main
2024/02/11 06:42:15.851687 compiling function literal main
panic: not implemented: *ast.IndexListExpr [recovered]
	panic: not implemented: *ast.IndexListExpr

goroutine 1 [running]:
...
...
...
```

**Comment by iamrajiv** [comment]
Hi @achille-roussel,

After investigation, I found that the panic originates from the `substituteTypeArgs` function in the `types.go` file. It seems like there's an attempt to use `*ast.IndexListExpr`, which is not implemented or supported, leading to the panic.

To resolve the panic related to `*ast.IndexListExpr`, we need to address the case of `*ast.IndexListExpr` in the `substituteTypeArgs` function. Since `*ast.IndexListExpr` is not implemented in the provided code, we have two options: either implement it or replace its usage with a supported feature.

**Comment by chriso** [comment]
Fixed by https://github.com/dispatchrun/coroutine/pull/148
